#!/bin/sh
# Render NUT configuration from the environment.
#
# Usage: render-config.sh [driver|server]
#
# Rule: a file that already exists is never touched. Bind-mount /etc/nut/ups.conf
# (or any other config) and this script leaves it exactly as you wrote it, which
# is how multi-UPS and mixed-vendor setups are meant to be configured.
#
# The role narrows what gets rendered: a driver needs only ups.conf, so driver
# containers do not have to be handed the upsd credentials.
set -eu

ROLE="${1:-server}"

NUT_CONF_DIR="${NUT_CONF_DIR:-/etc/nut}"

log()  { echo "nut-snmp: $*" >&2; }
die()  { log "error: $*"; exit 1; }

# Resolve VAR from ${VAR}_FILE when present, so Docker/compose secrets work.
resolve_secret() {
    _var="$1"
    eval "_file=\${${_var}_FILE:-}"
    [ -n "$_file" ] || return 0
    [ -r "$_file" ] || die "${_var}_FILE points at $_file, which is not readable"
    eval "_cur=\${${_var}:-}"
    [ -z "$_cur" ] || log "warning: both $_var and ${_var}_FILE are set; using ${_var}_FILE"
    _val="$(cat "$_file")"
    # This script is exec'd standalone, so the value only has to survive until
    # the render functions below read it -- no export needed.
    eval "${_var}=\$_val"
}

# emit_opt <key> <value> — skip silently when the value is empty, so NUT's own
# defaults stay in force instead of us writing something we invented.
emit_opt() {
    [ -n "${2:-}" ] || return 0
    printf '    %s = %s\n' "$1" "$2"
}

render_ups_conf() {
    _target="$NUT_CONF_DIR/ups.conf"
    if [ -e "$_target" ]; then
        log "using existing $_target"
        return 0
    fi
    [ -n "${SNMP_HOST:-}" ] || die "no $_target was mounted and SNMP_HOST is unset.
  Either bind-mount a ups.conf (required for more than one UPS, or for mixed
  vendors), or set SNMP_HOST for the single-UPS environment path."

    resolve_secret SNMP_COMMUNITY
    resolve_secret SNMP_AUTH_PASSWORD
    resolve_secret SNMP_PRIV_PASSWORD

    {
        printf '# Generated by nut-snmp from the environment. Mount your own\n'
        printf '# %s to take over completely.\n\n' "$_target"
        printf '[%s]\n' "${UPS_NAME:-ups}"
        printf '    driver = snmp-ups\n'
        printf '    port = %s\n' "$SNMP_HOST"
        # NUT's own default is v1; v2c is the deliberate default here.
        emit_opt snmp_version "${SNMP_VERSION:-v2c}"
        emit_opt community    "${SNMP_COMMUNITY:-public}"
        emit_opt mibs         "${MIBS:-auto}"
        emit_opt pollfreq     "${POLLFREQ:-}"
        emit_opt snmp_retries "${SNMP_RETRIES:-}"
        emit_opt snmp_timeout "${SNMP_TIMEOUT:-}"
        emit_opt secLevel     "${SNMP_SEC_LEVEL:-}"
        emit_opt secName      "${SNMP_SEC_NAME:-}"
        emit_opt authPassword "${SNMP_AUTH_PASSWORD:-}"
        emit_opt privPassword "${SNMP_PRIV_PASSWORD:-}"
        emit_opt authProtocol "${SNMP_AUTH_PROTOCOL:-}"
        emit_opt privProtocol "${SNMP_PRIV_PROTOCOL:-}"
        [ -z "${DESC:-}" ] || printf '    desc = "%s"\n' "$DESC"
        [ -z "${EXTRA_UPS_CONF:-}" ] || printf '%s\n' "$EXTRA_UPS_CONF"
    } > "$_target"
    log "generated $_target for UPS '${UPS_NAME:-ups}' at $SNMP_HOST"
}

render_upsd_conf() {
    _target="$NUT_CONF_DIR/upsd.conf"
    if [ -e "$_target" ]; then
        log "using existing $_target"
        return 0
    fi
    {
        printf 'LISTEN %s %s\n' "${LISTEN_ADDR:-0.0.0.0}" "${LISTEN_PORT:-3493}"
        [ -z "${MAXAGE:-}" ] || printf 'MAXAGE %s\n' "$MAXAGE"
    } > "$_target"
}

render_upsd_users() {
    _target="$NUT_CONF_DIR/upsd.users"
    if [ -e "$_target" ]; then
        log "using existing $_target"
        return 0
    fi
    resolve_secret NUT_PASSWORD
    [ -n "${NUT_PASSWORD:-}" ] || die "no $_target was mounted and NUT_PASSWORD is unset.
  Set NUT_PASSWORD (or NUT_PASSWORD_FILE) to the password your client, e.g.
  PeaNUT, will authenticate with."
    {
        printf '[%s]\n' "${NUT_USER:-nutmon}"
        printf '    password = %s\n' "$NUT_PASSWORD"
        # 2.8 spelling; "slave" is deprecated but still accepted upstream.
        printf '    upsmon secondary\n'
    } > "$_target"
}

# upsd never reads this, but upsdrvctl and nut-scanner do, so anyone who execs
# into the container to poke around gets a sane answer instead of a warning.
render_nut_conf() {
    _target="$NUT_CONF_DIR/nut.conf"
    [ -e "$_target" ] || printf 'MODE=netserver\n' > "$_target"
}

secure_configs() {
    # upsd refuses to start on a world-readable upsd.users. Running unprivileged
    # (docker run --user) makes chown impossible; that is fine as long as the
    # mounted files are already readable by the runtime user.
    for _f in ups.conf upsd.conf upsd.users nut.conf; do
        [ -e "$NUT_CONF_DIR/$_f" ] || continue
        [ -w "$NUT_CONF_DIR/$_f" ] || continue   # read-only bind mount: leave alone
        chown root:nut "$NUT_CONF_DIR/$_f" 2>/dev/null || true
        chmod 0640     "$NUT_CONF_DIR/$_f" 2>/dev/null || true
    done
}

mkdir -p "$NUT_CONF_DIR"
render_ups_conf
render_nut_conf
if [ "$ROLE" = "server" ]; then
    render_upsd_conf
    render_upsd_users
fi
secure_configs
